### ISSUE TITLE
Webpack .d.ts issue

### ISSUE THREAD

**Issue by kutyel** [GlobalWebIndex/d3scription#10]
Hi, I'm getting this error when trying to use this package from TypeScript 🤔 

```sh
✖ ｢wdm｣: ERROR in ./node_modules/d3scription/index.ts 3:7
Module parse failed: Unexpected token (3:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /// <reference path="d/d3.d.ts" />
| 
> export interface Offset {
|     top? : number;
|     left? : number;
 @ ./node_modules/d3-charts-2/dist/utils/tip.js 1:0-33 1:127-128
 @ ./node_modules/d3-charts-2/dist/charts/pie-radar-chart.js 1:35-103 1:641-642 3:132-133 3:202-203
 @ ./node_modules/d3-charts-2/index.js 4:20-60
 @ ./client/_x-tag/x-dashboards-chart-2/component.js 3:15-37
 @ ./client/app-monolithic/src/index.ts 70:0-57
 @ ./client/index.ts 2:0-30
```

**Comment by turboMaCk** [comment]
citing the error:

> You may need an appropriate loader to handle this file type,

I think problem is with your webpack configuration - it tries to process s file as js file. Likely you need to tweak your loaders and `resolve` config.

**Comment by turboMaCk** [comment]
also I don't think this is related to `.d.ts` at all. The issue is with parsing `index.ts` file which is typescript but is parsed as js so it fails on `interface` keyword.

**Comment by kutyel** [comment]
Right, I needed to parse `node_modules` through the `ts-loader` as well and it worked, sorry for the trouble 🙈
